services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --url http://host.docker.internal:8086/0/stream --no-chunked-encoding run motion
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    extra_hosts:
      - "host.docker.internal:host-gateway"
