services:
  ping:
    image: quay.io/prometheus/blackbox-exporter:latest
    restart: always
    command: --config.file=/config/blackbox.yml
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    ports:
      - 9115:9115
  snmp:
    image: prom/snmp-exporter
    network_mode: host
    restart: always
    volumes:
      - './snmp.yml:/etc/snmp_exporter/snmp.yml'
