services:
  app:
    image: ghcr.io/yude/annict-activity-to-mastodon:master
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
