version: "3.8"
services:
  web:
    restart: always
    image: mrbrax/twitchautomator:master
    volumes:
      - ./data:/usr/local/share/twitchautomator/data
    environment:
      - NODE_ENV=production
      - TCD_ENABLE_FILES_API=0
      - TCD_EXPOSE_LOGS_TO_PUBLIC=0
      - TCD_MIGRATE_OLD_VOD_JSON=0
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN