services:
  caddy:
    image: caddy
    restart: always
    volumes:
      - /mnt/store3/html:/usr/share/caddy
      - /mnt/store3/teltty:/usr/share/caddy/teltty
      - ./Caddyfile:/etc/caddy/Caddyfile

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
