version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - DOMAIN=https://vault.yude.jp
      - WEBSOCKET_ENABLED=true
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
