services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      TZ: "Asia/Tokyo"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    image: ghcr.io/yude/youbine:master
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
    depends_on:
      - db

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
