services:
  200ok:
    image: ghcr.io/yude/200ok:master
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
